[package]
name = "rust-blockchain"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
sha2 = "0.10"
ripemd = "0.1" 
hex = "0.4"
num-bigint = "0.4"
num-traits = "0.2"
bincode = "1.3"
serde = {version = "1.0", features = ["derive"] }
